from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, Field

AlertSeverity = Literal["critical", "high", "medium", "low", "info", "unknown"]
AlertStatus = Literal["firing", "resolved", "acknowledged", "suppressed"]


class AlertEvent(BaseModel):
    """Unified alert event used internally by Hubble."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    source: str
    title: str
    description: str = ""
    severity: AlertSeverity = "unknown"
    status: AlertStatus = "firing"
    labels: dict[str, str] = Field(default_factory=dict)
    annotations: dict[str, str] = Field(default_factory=dict)
    starts_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    ends_at: datetime | None = None
    fingerprint: str | None = None
    raw: dict[str, Any] = Field(default_factory=dict)

    def stable_fingerprint(self) -> str:
        """Generate a stable fingerprint for deduplication and incident grouping."""
        if self.fingerprint:
            return self.fingerprint

        payload = {
            "source": self.source,
            "title": self.title,
            "labels": self.labels,
        }
        encoded = json.dumps(payload, sort_keys=True, ensure_ascii=False).encode("utf-8")
        return hashlib.sha256(encoded).hexdigest()[:24]


class ToolCallRequest(BaseModel):
    """A model-requested tool call. Execution is controlled by Hubble, not the model."""

    tool_name: str
    params: dict[str, Any] = Field(default_factory=dict)
    reason: str = ""


class ToolResult(BaseModel):
    ok: bool
    data: Any | None = None
    error: str | None = None
    elapsed_ms: int | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class AlertAnalysis(BaseModel):
    """Structured analysis generated by model orchestration layer."""

    summary: str
    severity: AlertSeverity = "unknown"
    possible_causes: list[str] = Field(default_factory=list)
    impact: str = ""
    recommended_actions: list[str] = Field(default_factory=list)
    tool_requests: list[ToolCallRequest] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    raw_response: str | None = None


class Notification(BaseModel):
    """Message sent to humans through a notifier."""

    title: str
    body: str
    severity: AlertSeverity = "unknown"
    alert_id: str | None = None
    incident_id: str | None = None
    channel: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class SendResult(BaseModel):
    ok: bool
    message_id: str | None = None
    error: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class SessionMessage(BaseModel):
    """Message received from a chat session such as Feishu, WeCom or CLI."""

    channel: str
    thread_id: str | None = None
    sender_id: str | None = None
    text: str
    alert_id: str | None = None
    incident_id: str | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)
