from __future__ import annotations

from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from hubble.alerts.models import AlertSeverity


class ToolCallRequest(BaseModel):
    tool_name: str
    params: dict[str, Any] = Field(default_factory=dict)
    reason: str = ""


class Analysis(BaseModel):
    """Structured analysis generated by the reasoning layer."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    alert_id: str | None = None
    incident_id: str | None = None
    summary: str
    severity: AlertSeverity = "unknown"
    possible_causes: list[str] = Field(default_factory=list)
    impact: str = ""
    recommended_actions: list[str] = Field(default_factory=list)
    tool_requests: list[ToolCallRequest] = Field(default_factory=list)
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    model_provider: str | None = None
    prompt_version: str | None = None
    raw_response: str | None = None
